//! Fixture-driven fidelity tests that compare Rust `ad-core`
//! against reference values computed by the actual JS game code.
//!
//! The fixture file `fixtures/pre-infinity.json` is generated by
//! running `node generate-fixtures.js` in the `js-harness/`
//! directory, which loads and executes the original Antimatter
//! Dimensions source code.

use std::fs;
use std::path::PathBuf;

use ad_core::{Decimal, GameState};
use ad_fidelity::tolerance::{assert_approx_eq, assert_approx_eq_f64, EPSILON_EXACT};
use serde::Deserialize;

// ============================================================
// Fixture data structures
// ============================================================

#[derive(Deserialize)]
#[allow(dead_code)]
struct Fixtures {
    dimension_costs: Vec<CostEntry>,
    buy10_multiplier_base: f64,
    buy10_multiplier: Vec<Buy10Entry>,
    dimboost_multiplier: Vec<DimboostMultEntry>,
    dimboost_requirements: Vec<DimboostReqEntry>,
    tickspeed_multiplier: Vec<TickspeedEntry>,
    galaxy_requirements: Vec<GalaxyReqEntry>,
    sacrifice: SacrificeFixtures,
    dimension_multipliers: Vec<DimMultEntry>,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct CostEntry {
    tier: usize,
    bought: u64,
    cost: String,
    log10_cost: f64,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct Buy10Entry {
    bought: u64,
    groups: u64,
    multiplier: String,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct DimboostMultEntry {
    boosts: u32,
    tier: usize,
    multiplier: String,
    log10_multiplier: f64,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct DimboostReqEntry {
    current_boosts: u32,
    required_tier: usize,
    required_amount: u64,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct TickspeedEntry {
    galaxies: u32,
    multiplier: String,
    multiplier_f64: f64,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct GalaxyReqEntry {
    galaxies: u32,
    required_tier: usize,
    required_amount: u64,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct SacrificeFixtures {
    total_boost: Vec<TotalBoostEntry>,
    next_boost: Vec<NextBoostEntry>,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct TotalBoostEntry {
    log10_sacrificed: u32,
    total_boost: String,
    log10_total_boost: Option<f64>,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct NextBoostEntry {
    log10_ad1: u32,
    log10_sacrificed: u32,
    next_boost: String,
}

#[derive(Deserialize)]
#[allow(dead_code)]
struct DimMultEntry {
    tier: usize,
    boosts: u32,
    bought: u64,
    galaxies: u32,
    multiplier: String,
    log10_multiplier: Option<f64>,
}

fn load_fixtures() -> Fixtures {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("fixtures");
    path.push("pre-infinity.json");
    let data = fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "Failed to read fixtures at {}: {}\n\
             Run `cd js-harness && node generate-fixtures.js` \
             to generate them.",
            path.display(),
            e,
        )
    });
    serde_json::from_str(&data).expect("Failed to parse fixtures")
}

fn parse_decimal(s: &str) -> Decimal {
    // Handle scientific notation like "1e+31"
    let s = s.replace("e+", "e");
    s.parse::<Decimal>()
        .unwrap_or_else(|_| panic!("Failed to parse Decimal: {s}"))
}

// ============================================================
// Tests
// ============================================================

/// Section 1: Verify dimension costs against JS reference.
#[test]
fn fixture_dimension_costs() {
    let fixtures = load_fixtures();
    let mut state = GameState::new();

    for entry in &fixtures.dimension_costs {
        // tier in fixtures is 1-indexed; ad-core is 0-indexed
        let tier = entry.tier - 1;
        state.dimensions[tier].bought = entry.bought;

        let cost = state.dimension_cost(tier);
        let expected = parse_decimal(&entry.cost);

        assert_approx_eq(
            cost,
            expected,
            EPSILON_EXACT,
            &format!("AD{} cost at bought={}", entry.tier, entry.bought),
        );

        // Reset for next iteration
        state.dimensions[tier].bought = 0;
    }
}

/// Section 2: Verify buy-10 multiplier base is 2.
#[test]
fn fixture_buy10_multiplier_base() {
    let fixtures = load_fixtures();
    assert_approx_eq_f64(
        fixtures.buy10_multiplier_base,
        2.0,
        EPSILON_EXACT,
        "buy10 multiplier base",
    );
}

/// Section 3: Verify dim boost multiplier (tier-dependent).
#[test]
fn fixture_dimboost_multiplier() {
    let fixtures = load_fixtures();
    let mut state = GameState::new();

    for entry in &fixtures.dimboost_multiplier {
        state.dim_boosts = entry.boosts;
        // tier in fixtures is 1-indexed
        let tier = entry.tier - 1;

        let mult = state.dimension_multiplier(tier);
        let expected = parse_decimal(&entry.multiplier);

        // The JS multiplier only includes dimboost component.
        // The Rust multiplier includes buy10 (=1 when bought=0)
        // and sacrifice (=1 for default). So with bought=0,
        // they should match.
        assert_approx_eq(
            mult,
            expected,
            EPSILON_EXACT,
            &format!(
                "dimboost mult: boosts={}, tier={}",
                entry.boosts, entry.tier
            ),
        );
    }
}

/// Section 3b: Verify dim boost requirements.
#[test]
fn fixture_dimboost_requirements() {
    let fixtures = load_fixtures();
    let mut state = GameState::new();

    for entry in &fixtures.dimboost_requirements {
        state.dim_boosts = entry.current_boosts;
        let (tier, amount) = state.dim_boost_requirement();

        // JS tier is 1-indexed, Rust is 0-indexed
        assert_eq!(
            tier + 1,
            entry.required_tier,
            "dimboost req tier at boosts={}",
            entry.current_boosts,
        );
        assert_eq!(
            amount, entry.required_amount,
            "dimboost req amount at boosts={}",
            entry.current_boosts,
        );
    }
}

/// Section 4: Verify tickspeed purchase multiplier.
#[test]
fn fixture_tickspeed_multiplier() {
    let fixtures = load_fixtures();
    let mut state = GameState::new();

    for entry in &fixtures.tickspeed_multiplier {
        state.galaxies = entry.galaxies;
        let mult = state.tickspeed_purchase_multiplier();

        assert_approx_eq_f64(
            mult,
            entry.multiplier_f64,
            EPSILON_EXACT,
            &format!("tickspeed mult at {} galaxies", entry.galaxies),
        );
    }
}

/// Section 5: Verify galaxy requirements.
#[test]
fn fixture_galaxy_requirements() {
    let fixtures = load_fixtures();
    let mut state = GameState::new();

    for entry in &fixtures.galaxy_requirements {
        state.galaxies = entry.galaxies;
        let req = state.galaxy_requirement();

        // JS required_tier is 1-indexed (tier 8)
        // Our galaxy_requirement returns just the amount (tier
        // is always 8 in pre-infinity).
        assert_eq!(
            entry.required_tier, 8,
            "galaxy always requires tier 8 in pre-infinity"
        );
        assert_eq!(
            req, entry.required_amount,
            "galaxy req at galaxies={}",
            entry.galaxies,
        );
    }
}

/// Section 6a: Verify sacrifice totalBoost.
#[test]
fn fixture_sacrifice_total_boost() {
    let fixtures = load_fixtures();

    for entry in &fixtures.sacrifice.total_boost {
        let expected = parse_decimal(&entry.total_boost);

        // Compute using the JS formula directly:
        // max(1, log10(sacrificed)/10)^2
        let log_sacrificed = entry.log10_sacrificed as f64;
        let log_val = (log_sacrificed / 10.0).max(1.0);
        let computed = Decimal::from_float(log_val.powf(2.0));

        assert_approx_eq(
            computed,
            expected,
            EPSILON_EXACT,
            &format!(
                "sacrifice totalBoost at log10_sacrificed={}",
                entry.log10_sacrificed
            ),
        );
    }
}

/// Section 6b: Verify sacrifice nextBoost.
#[test]
fn fixture_sacrifice_next_boost() {
    let fixtures = load_fixtures();

    for entry in &fixtures.sacrifice.next_boost {
        let mut state = GameState::new();
        state.dim_boosts = 5;
        state.sacrifice_unlocked = true;
        state.dimensions[0].amount =
            Decimal::from_float(10.0_f64.powi(entry.log10_ad1 as i32));
        state.sacrificed =
            Decimal::from_float(10.0_f64.powi(entry.log10_sacrificed as i32));
        state.sacrifice_boost = Decimal::ONE;

        let expected = parse_decimal(&entry.next_boost);
        let actual = state.sacrifice_multiplier_if_sacrificed();

        assert_approx_eq(
            actual,
            expected,
            EPSILON_EXACT,
            &format!(
                "sacrifice nextBoost: AD1=1e{}, sacrificed=1e{}",
                entry.log10_ad1, entry.log10_sacrificed
            ),
        );
    }
}

/// Section 7: Verify full dimension multiplier.
///
/// The JS `getDimensionFinalMultiplierUncached` includes:
///   commonMultiplier (=1) × buy10 × dimboost × sacrifice ×
///   various effects (all =1 in pre-infinity)
///
/// Our `dimension_multiplier` includes the same components.
#[test]
fn fixture_dimension_multipliers() {
    let fixtures = load_fixtures();

    for entry in &fixtures.dimension_multipliers {
        let mut state = GameState::new();
        state.dim_boosts = entry.boosts;
        state.galaxies = entry.galaxies;

        let tier = entry.tier - 1;
        state.dimensions[tier].bought = entry.bought;
        state.dimensions[tier].amount = Decimal::from_float(entry.bought as f64);

        let expected = parse_decimal(&entry.multiplier);
        let actual = state.dimension_multiplier(tier);

        assert_approx_eq(
            actual,
            expected,
            EPSILON_EXACT,
            &format!(
                "dim mult: tier={}, boosts={}, bought={}, \
                 galaxies={}",
                entry.tier, entry.boosts, entry.bought, entry.galaxies,
            ),
        );
    }
}
