//! ad-gui backend entry point: Tauri setup, managed state, and the command
//! registration. The `GameView` snapshot lives in `views.rs`, the command
//! layer in `commands.rs`, and on-disk persistence in `persistence.rs`.

mod commands;
mod persistence;
mod views;

use std::path::PathBuf;
use std::sync::Mutex;

use ad_core::GameState;
use tauri::Manager;

use commands::{fresh_game, PendingOffline};
use persistence::{now_ms, SaveManager};

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .manage(Mutex::new(fresh_game()))
        .manage(PendingOffline::default())
        .setup(|app| {
            // Resolve the OS app-data dir (§12.1), load the on-disk root save into
            // the running game, and install the SaveManager. A missing/corrupt
            // save just starts fresh.
            let dir = app
                .path()
                .app_data_dir()
                .unwrap_or_else(|_| PathBuf::from("."));
            let mut manager = SaveManager::new(dir);
            let (loaded, offline_ms) = manager.load(fresh_game(), now_ms());
            *app.state::<Mutex<GameState>>().lock().unwrap() = loaded;
            // Stash the away-time for the frontend to replay as offline progress
            // once it has mounted (see take_pending_offline).
            *app.state::<PendingOffline>().0.lock().unwrap() = offline_ms as f64;
            app.manage(Mutex::new(manager));
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            commands::tick_and_get_state,
            commands::simulate_offline,
            commands::offline_plan,
            commands::get_state,
            commands::take_pending_offline,
            commands::buy_dimension,
            commands::buy_until_10,
            commands::buy_tickspeed,
            commands::buy_max_tickspeed,
            commands::buy_dim_boost,
            commands::buy_galaxy,
            commands::sacrifice,
            commands::max_all,
            commands::big_crunch,
            commands::eternity,
            commands::buy_time_dimension,
            commands::buy_max_time_dimension,
            commands::max_all_time_dimensions,
            commands::buy_time_study,
            commands::buy_dilation_study,
            commands::buy_dilation_upgrade,
            commands::toggle_dilation,
            commands::buy_eternity_upgrade,
            commands::buy_ep_mult,
            commands::buy_max_ep_mult,
            commands::buy_ec_study,
            commands::start_eternity_challenge,
            commands::exit_eternity_challenge,
            commands::buy_time_theorem,
            commands::buy_max_time_theorems,
            commands::set_respec,
            commands::break_infinity,
            commands::do_reality,
            commands::reset_reality,
            commands::equip_glyph,
            commands::sacrifice_glyph,
            commands::move_glyph,
            commands::set_glyph_respec,
            commands::buy_perk,
            commands::buy_reality_rebuyable,
            commands::buy_reality_upgrade,
            commands::teresa_pour_rm,
            commands::teresa_stop_pouring,
            commands::buy_perk_shop,
            commands::effarig_buy_unlock,
            commands::toggle_store_game_time,
            commands::enslaved_release,
            commands::buy_enslaved_unlock,
            commands::buy_tesseract,
            commands::toggle_store_real_time,
            commands::toggle_auto_store_real,
            commands::toggle_boost_reality,
            commands::toggle_auto_release,
            commands::charge_infinity_upgrade,
            commands::discharge_infinity_upgrade,
            commands::toggle_discharge,
            commands::v_reduce_goal,
            commands::toggle_dmd_autobuyer,
            commands::toggle_ascension_autobuyer,
            commands::toggle_annihilation_autobuyer,
            commands::set_annihilation_multiplier,
            commands::toggle_singularity_autobuyer,
            commands::toggle_auto_auto_clean,
            commands::toggle_apply_filter_to_purge,
            commands::glyph_purge,
            commands::give_cursed_glyph,
            commands::save_glyph_set,
            commands::load_glyph_set,
            commands::delete_glyph_set,
            commands::v_unlock_celestial,
            commands::start_celestial_reality,
            commands::ra_level_up,
            commands::ra_buy_memory_upgrade,
            commands::ra_buy_chunk_upgrade,
            commands::ra_set_remembrance,
            commands::alchemy_toggle_reaction,
            commands::dmd_buy_upgrade,
            commands::dmd_ascend,
            commands::laitela_max_all_dmd,
            commands::laitela_annihilate,
            commands::laitela_condense_singularity,
            commands::laitela_set_continuum,
            commands::laitela_change_singularity_cap,
            commands::buy_imaginary_upgrade,
            commands::buy_imaginary_rebuyable,
            commands::doom_reality,
            commands::pelle_armageddon,
            commands::pelle_toggle_rift,
            commands::buy_pelle_upgrade,
            commands::buy_pelle_rebuyable,
            commands::pelle_start_sacrifice,
            commands::unlock_black_hole,
            commands::buy_black_hole_upgrade,
            commands::toggle_black_hole_pause,
            commands::set_black_hole_negative,
            commands::set_black_hole_auto_pause,
            commands::buy_break_infinity_upgrade,
            commands::buy_break_infinity_rebuyable,
            commands::buy_infinity_dimension,
            commands::buy_max_infinity_dimension,
            commands::buy_max_all_infinity_dimensions,
            commands::unlock_replicanti,
            commands::tab_notification_seen,
            commands::buy_replicanti_chance,
            commands::buy_replicanti_interval,
            commands::buy_replicanti_galaxy_cap,
            commands::buy_replicanti_galaxy,
            commands::buy_infinity_upgrade,
            commands::buy_ip_mult,
            commands::buy_max_ip_mult,
            commands::buy_ip_offline,
            commands::set_ip_mult_autobuyer,
            commands::undo_glyph,
            commands::set_glyph_weights,
            commands::create_reality_glyph,
            commands::set_glyph_filter_modes,
            commands::set_glyph_filter_type,
            commands::offline_currency_gain,
            commands::start_challenge,
            commands::exit_challenge,
            commands::start_infinity_challenge,
            commands::hard_reset,
            commands::unlock_ad_autobuyer,
            commands::toggle_ad_autobuyer,
            commands::toggle_ad_autobuyer_mode,
            commands::unlock_tickspeed_autobuyer,
            commands::toggle_tickspeed_autobuyer,
            commands::toggle_autobuyers,
            commands::set_all_autobuyers_active,
            commands::upgrade_autobuyer_interval,
            commands::upgrade_ad_autobuyer_bulk,
            commands::toggle_milestone_autobuyer,
            commands::toggle_autobuyer,
            commands::set_hotkeys,
            commands::set_update_rate,
            commands::set_stat_tab_resources,
            commands::toggle_shown_runs,
            commands::set_notation,
            commands::set_notation_digits,
            commands::set_offline_ticks,
            commands::set_animation,
            commands::set_hint_text,
            commands::set_away_progress,
            commands::set_header_text_colored,
            commands::set_retry_challenge,
            commands::set_sidebar_resource,
            commands::toggle_tab_visibility,
            commands::unhide_tab,
            commands::toggle_subtab_visibility,
            commands::show_all_tabs,
            commands::set_confirmation,
            commands::set_autosave_interval,
            commands::set_show_time_since_save,
            commands::set_save_file_name,
            commands::export_save,
            commands::import_save,
            commands::export_save_to_file,
            commands::import_save_from_file,
            commands::save_game,
            commands::set_prestige_autobuyer_mode,
            commands::set_prestige_autobuyer_value,
            commands::toggle_autobuyer_dynamic_amount,
            commands::set_reality_autobuyer_mode,
            commands::set_reality_autobuyer_value,
            commands::study_preset_save,
            commands::study_preset_load,
            commands::study_preset_rename,
            commands::study_preset_edit,
            commands::study_tree_export,
            commands::study_tree_is_valid,
            commands::automator_play,
            commands::automator_stop,
            commands::automator_rewind,
            commands::automator_step,
            commands::automator_toggle_setting,
            commands::automator_select_script,
            commands::automator_new_script,
            commands::automator_rename_script,
            commands::automator_delete_script,
            commands::get_automator_script,
            commands::save_automator_script,
            commands::get_automator_errors,
            commands::automator_set_constant,
            commands::automator_rename_constant,
            commands::automator_delete_constant,
            commands::automator_set_info_pane,
            commands::get_automator_events,
            commands::automator_clear_log,
            commands::set_automator_event_option,
            commands::automator_blockify,
            commands::automator_blockify_text,
            commands::automator_set_editor_type,
            commands::automator_template,
            commands::automator_export_script,
            commands::automator_export_full,
            commands::automator_import_preview,
            commands::automator_import,
            commands::automator_script_data_info,
            commands::switch_save_slot,
            commands::get_save_slots,
            commands::trigger_backup,
            commands::get_backups,
            commands::load_backup,
            commands::export_backups_to_file,
            commands::import_backups_from_file,
        ])
        .run(tauri::generate_context!())
        .expect("error running tauri application");
}

fn main() {
    run();
}
