//! Black-box fidelity tests: `format(value, opts)` -> string, checked against
//! ground truth from the real `@antimatter-dimensions/notations` v3.1.0 package.
//!
//! Generated by `gen_format_cases.mjs` (alongside this file); see the design doc
//! `design-docs/2026-06-28-ad-format-test-plan.md`. Regenerate with:
//!     node crates/ad-format/tests/gen_format_cases.mjs > crates/ad-format/tests/format_edge_cases.rs
//!     cargo fmt -p ad-format
//!
//! Values are parsed identically on both sides (both are break_infinity ports), so
//! the only variable under test is the formatting logic. Do not hand-edit expected
//! strings; regenerate instead.

use ad_format::{format, ExponentDisplay, FormatOptions, Notation};
use break_infinity::Decimal;

fn d(s: &str) -> Decimal {
    s.parse().expect("valid Decimal literal")
}

const DEF_ED: ExponentDisplay = ExponentDisplay {
    show: true,
    min: 100_000,
    max: 1_000_000_000,
};

/// Compact FormatOptions builder mirroring the JS call `format(v, places, pu, pe)`
/// plus the global `Settings` (exponent display, infinite threshold).
fn o(
    notation: Notation,
    places: u32,
    pu: u32,
    pe: u32,
    exponent_display: ExponentDisplay,
    inf: Option<&str>,
) -> FormatOptions {
    FormatOptions {
        notation,
        places,
        places_under_1000: pu,
        places_exponent: pe,
        exponent_display,
        inf_threshold: inf.map(d),
    }
}

#[test]
fn infinite_threshold() {
    // inf-threshold boundary, sign, and non-Scientific notations
    assert_eq!(
        format(
            &d("1e308"),
            &o(Notation::Scientific, 2, 0, 3, DEF_ED, Some("1e308"))
        ),
        "Infinite"
    );
    assert_eq!(
        format(
            &d("9.99e307"),
            &o(Notation::Scientific, 2, 0, 3, DEF_ED, Some("1e308"))
        ),
        "9.99e307"
    );
    assert_eq!(
        format(
            &d("-1e308"),
            &o(Notation::Scientific, 2, 0, 3, DEF_ED, Some("1e308"))
        ),
        "-Infinite"
    );
    assert_eq!(
        format(&d("1e309"), &o(Notation::Scientific, 2, 0, 3, DEF_ED, None)),
        "1.00e309"
    );
    assert_eq!(
        format(
            &d("1e308"),
            &o(Notation::Standard, 2, 0, 3, DEF_ED, Some("1e308"))
        ),
        "Infinite"
    );
    assert_eq!(
        format(
            &d("-1e308"),
            &o(Notation::Letters, 2, 0, 3, DEF_ED, Some("1e308"))
        ),
        "-Infinite"
    );
}

#[test]
fn region_boundaries() {
    // exponent -300/-301 and 2/3 region splits, very-small sign
    assert_eq!(
        format(
            &d("1e-300"),
            &o(Notation::Scientific, 2, 0, 3, DEF_ED, None)
        ),
        "0"
    );
    assert_eq!(
        format(
            &d("1e-300"),
            &o(Notation::Scientific, 2, 2, 3, DEF_ED, None)
        ),
        "0.00"
    );
    assert_eq!(
        format(
            &d("1e-301"),
            &o(Notation::Scientific, 2, 0, 3, DEF_ED, None)
        ),
        "0"
    );
    assert_eq!(
        format(
            &d("1e-301"),
            &o(Notation::Scientific, 2, 2, 3, DEF_ED, None)
        ),
        "0.00"
    );
    assert_eq!(
        format(
            &d("-1e-310"),
            &o(Notation::Scientific, 2, 0, 3, DEF_ED, None)
        ),
        "-0"
    );
    assert_eq!(
        format(
            &d("-1e-310"),
            &o(Notation::Scientific, 2, 2, 3, DEF_ED, None)
        ),
        "-0.00"
    );
    assert_eq!(
        format(
            &d("9.99e2"),
            &o(Notation::Scientific, 2, 0, 3, DEF_ED, None)
        ),
        "999"
    );
    assert_eq!(
        format(&d("1e3"), &o(Notation::Scientific, 2, 0, 3, DEF_ED, None)),
        "1.00e3"
    );
}

#[test]
fn small_all_notations() {
    // under-1000 + negatives for Standard and Letters
    assert_eq!(
        format(&d("4.2e1"), &o(Notation::Standard, 2, 0, 3, DEF_ED, None)),
        "42"
    );
    assert_eq!(
        format(&d("-4.2e1"), &o(Notation::Standard, 2, 0, 3, DEF_ED, None)),
        "-42"
    );
    assert_eq!(
        format(&d("4.2e1"), &o(Notation::Letters, 2, 0, 3, DEF_ED, None)),
        "42"
    );
    assert_eq!(
        format(&d("-4.2e1"), &o(Notation::Letters, 2, 0, 3, DEF_ED, None)),
        "-42"
    );
}

#[test]
fn negative_big() {
    // sign path for non-Scientific big numbers
    assert_eq!(
        format(&d("-1e6"), &o(Notation::Standard, 2, 0, 3, DEF_ED, None)),
        "-1.00 M"
    );
    assert_eq!(
        format(&d("-1.5e10"), &o(Notation::Letters, 2, 0, 3, DEF_ED, None)),
        "-15.00c"
    );
    assert_eq!(
        format(
            &d("-1.23456e100"),
            &o(Notation::Engineering, 2, 0, 3, DEF_ED, None)
        ),
        "-12.35e99"
    );
}

#[test]
fn exponent_display() {
    // show=false, exact min/max boundaries, custom min/max
    assert_eq!(
        format(
            &d("1e100000"),
            &o(
                Notation::Scientific,
                2,
                0,
                3,
                ExponentDisplay {
                    show: false,
                    min: 100000,
                    max: 1000000000
                },
                None
            )
        ),
        "1.00e1.000e5"
    );
    assert_eq!(
        format(
            &d("1e99999"),
            &o(
                Notation::Scientific,
                2,
                0,
                3,
                ExponentDisplay {
                    show: false,
                    min: 100000,
                    max: 1000000000
                },
                None
            )
        ),
        "1.00e99999"
    );
    assert_eq!(
        format(
            &d("1e100000"),
            &o(Notation::Scientific, 2, 0, 3, DEF_ED, None)
        ),
        "1.00e100,000"
    );
    assert_eq!(
        format(
            &d("1e99999"),
            &o(Notation::Scientific, 2, 0, 3, DEF_ED, None)
        ),
        "1.00e99999"
    );
    assert_eq!(
        format(
            &d("1e1000000000"),
            &o(Notation::Scientific, 2, 0, 3, DEF_ED, None)
        ),
        "1.00e1.000e9"
    );
    assert_eq!(
        format(
            &d("1e999999999"),
            &o(Notation::Scientific, 2, 0, 3, DEF_ED, None)
        ),
        "1.00e999,999,999"
    );
    assert_eq!(
        format(
            &d("1e5000"),
            &o(
                Notation::Scientific,
                2,
                0,
                3,
                ExponentDisplay {
                    show: true,
                    min: 10,
                    max: 100000
                },
                None
            )
        ),
        "1.00e5,000"
    );
    assert_eq!(
        format(
            &d("1e5"),
            &o(
                Notation::Scientific,
                2,
                0,
                3,
                ExponentDisplay {
                    show: true,
                    min: 10,
                    max: 100000
                },
                None
            )
        ),
        "1.00e5"
    );
    assert_eq!(
        format(
            &d("1e100000"),
            &o(
                Notation::Scientific,
                2,
                0,
                3,
                ExponentDisplay {
                    show: true,
                    min: 10,
                    max: 100000
                },
                None
            )
        ),
        "1.00e1.000e5"
    );
}

#[test]
fn places_exponent() {
    // nested mantissa places in the recursive branch (max(2))
    assert_eq!(
        format(
            &d("1e1000000000"),
            &o(Notation::Scientific, 2, 0, 0, DEF_ED, None)
        ),
        "1.00e1.00e9"
    );
    assert_eq!(
        format(
            &d("1e1000000000"),
            &o(Notation::Scientific, 2, 0, 4, DEF_ED, None)
        ),
        "1.00e1.0000e9"
    );
    assert_eq!(
        format(
            &d("1e1000000000000000"),
            &o(Notation::Scientific, 2, 0, 3, DEF_ED, None)
        ),
        "1.00e1.000e15"
    );
}

#[test]
fn standard_extra() {
    // roll-over into a new letter, places vs places_under_1000, regex paths
    assert_eq!(
        format(
            &d("9.99999e5"),
            &o(Notation::Standard, 2, 0, 3, DEF_ED, None)
        ),
        "1.00 M"
    );
    assert_eq!(
        format(&d("1.5e6"), &o(Notation::Standard, 3, 0, 3, DEF_ED, None)),
        "1.500 M"
    );
    assert_eq!(
        format(&d("1.5e2"), &o(Notation::Standard, 3, 1, 3, DEF_ED, None)),
        "150.0"
    );
    assert_eq!(
        format(&d("1e303"), &o(Notation::Standard, 2, 0, 3, DEF_ED, None)),
        "1.00 Ce"
    );
    assert_eq!(
        format(&d("1e6003"), &o(Notation::Standard, 2, 0, 3, DEF_ED, None)),
        "1.00 DMI"
    );
    assert_eq!(
        format(
            &d("1e100002"),
            &o(Notation::Standard, 2, 0, 3, DEF_ED, None)
        ),
        "1.00 TTgMI-TTgTc"
    );
}

#[test]
fn letters_extra() {
    // 3-letter transcription, residues, exponent-display ignored
    assert_eq!(
        format(&d("1e2109"), &o(Notation::Letters, 2, 0, 3, DEF_ED, None)),
        "1.00aaa"
    );
    assert_eq!(
        format(&d("1e2106"), &o(Notation::Letters, 2, 0, 3, DEF_ED, None)),
        "1.00zz"
    );
    assert_eq!(
        format(&d("1e9"), &o(Notation::Letters, 2, 0, 3, DEF_ED, None)),
        "1.00c"
    );
    assert_eq!(
        format(&d("1e10"), &o(Notation::Letters, 2, 0, 3, DEF_ED, None)),
        "10.00c"
    );
    assert_eq!(
        format(&d("1e11"), &o(Notation::Letters, 2, 0, 3, DEF_ED, None)),
        "100.00c"
    );
    assert_eq!(
        format(
            &d("1e1000002"),
            &o(Notation::Letters, 2, 0, 3, DEF_ED, None)
        ),
        "1.00rybn"
    );
    assert_eq!(
        format(
            &d("1e2109"),
            &o(
                Notation::Letters,
                2,
                0,
                0,
                ExponentDisplay {
                    show: false,
                    min: 100000,
                    max: 1000000000
                },
                None
            )
        ),
        "1.00aaa"
    );
}

#[test]
fn places_sweep() {
    // mantissa places 0/1/2/5
    assert_eq!(
        format(
            &d("1.23456e100"),
            &o(Notation::Scientific, 0, 0, 3, DEF_ED, None)
        ),
        "1e100"
    );
    assert_eq!(
        format(
            &d("1.23456e100"),
            &o(Notation::Scientific, 1, 0, 3, DEF_ED, None)
        ),
        "1.2e100"
    );
    assert_eq!(
        format(
            &d("1.23456e100"),
            &o(Notation::Scientific, 2, 0, 3, DEF_ED, None)
        ),
        "1.23e100"
    );
    assert_eq!(
        format(
            &d("1.23456e100"),
            &o(Notation::Scientific, 5, 0, 3, DEF_ED, None)
        ),
        "1.23456e100"
    );
}
